services:
  backend:
    build: ./backend
    image: backend
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
    ports:
      - "8080:8080"
    networks:
      - job-network
    depends_on:
      - db
#    volumes:
#      - ./src:/app/src
  frontend:
    image: angular
    container_name: angular-client
    build: ./frontend
    command: npm start
    ports:
      - "4200:4200"
    networks:
      - job-network
#    volumes:
#      - ./html5up-stellar/:/usr/share/nginx/html
#  nginx:
#    container_name: nginx
#    image: nginx:alpine
#    ports:
#      - "80:80"
#    networks:
#        - job-network
#    volumes:
#      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - backend
  db:
    image: postgres
    container_name: db
    build: ./database
#    restart: 'always'
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'data:/var/lib/postgresql/data'
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=secret'
#      - 'RABBITMQ_DEFAULT_USER=myuser'
#    ports:
#      - '5672'
volumes:
  data:

networks:
  job-network:
    driver: bridge