services:
  server:
    build: ./backend
    image: app
    ports:
      - "8080:8080"
  client:
    build: ./frontend
    ports:
      - "4200:80"
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=your_password'
      - 'POSTGRES_USER=your_username'
    ports:
      - '5432:5432'
    volumes:
      - 'data:/var/lib/postgresql/data'
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=secret'
#      - 'RABBITMQ_DEFAULT_USER=myuser'
#    ports:
#      - '5672'
volumes:
  data: