spring.datasource.url=jdbc:postgresql://postgres:5432/my_db
spring.datasource.username=helloUser
spring.datasource.password=doNotEnter312
spring.jpa.hibernate.ddl-auto=update
spring.data.rest.basePath=/api
