spring.datasource.url=jdbc:postgresql://postgres:5432/my_db
spring.datasource.username=helloUser
spring.datasource.password=doNotEnter312
spring.jpa.hibernate.ddl-auto=update
spring.data.rest.basePath=/api
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.jdbc.dialect=hsql