spring.datasource.url=jdbc:postgresql://postgres:localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password==mypassword
#spring.jpa.hibernate.ddl-auto=update
#spring.data.rest.basePath=/api
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect